import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import WebGIViewer from "./component/WebGIViewer";
import Navbar from "./component/Navbar";

const inter = Roboto_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-gray-900 text-white ${inter.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
